name: GDAL Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Install JAXB Dependencies
      run: |
        sudo apt-get install -y libjaxb-java
        sudo ln -s /usr/share/java/jaxb-api.jar ${ANDROID_SDK_ROOT}/tools/lib/jaxb-libs/jaxb-api.jar
        sudo ln -s /usr/share/java/jaxb-impl.jar ${ANDROID_SDK_ROOT}/tools/lib/jaxb-libs/jaxb-impl.jar
        sudo ln -s /usr/share/java/activation.jar ${ANDROID_SDK_ROOT}/tools/lib/jaxb-libs/activation.jar

    - name: Install NDK
      run: |
        sudo apt-get install -y ninja-build
        echo "y" | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install "ndk;21.4.7075529"

    - name: Build GDAL
      run: |
        git clone https://github.com/OSGeo/gdal.git
        cd gdal
        ./configure --host=aarch64-linux-android --with-proj=/usr/local --with-sqlite3=/usr/local --without-libtool
        make -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gdal-android
        path: gdal/swig/java/gdal.jar