name: GDAL Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e

    - name: Install Build Dependencies
      run: |
        sudo apt-get install -y ninja-build tcl libtiff-dev

    - name: Build SQLite3
      run: |
        git clone https://github.com/sqlite/sqlite.git
        cd sqlite
        ./configure --host=aarch64-linux-android --prefix=$GITHUB_WORKSPACE/sqlite-install
        make
        make install

    - name: Build TIFF 
      run: |
        git clone https://gitlab.com/libtiff/libtiff.git
        cd libtiff
        # Comment out line 156 to skip add_subdirectory(build)
        sed -i '156s/^/#/' CMakeLists.txt  
        rm -rf build
        cmake . \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/tiff-install
        cmake --build .
        cmake --install .

    - name: Build PROJ
      run: |
        git clone https://github.com/OSGeo/PROJ.git
        cd PROJ
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          -DTIFF_INCLUDE_DIR=$GITHUB_WORKSPACE/tiff-install/include \
          -DTIFF_LIBRARY=$GITHUB_WORKSPACE/tiff-install/lib/libtiff.a \
          -DSQLite3_INCLUDE_DIR=$GITHUB_WORKSPACE/sqlite-install/include \
          -DSQLite3_LIBRARY=$GITHUB_WORKSPACE/sqlite-install/lib/libsqlite3.a
        cmake --build .
        cmake --install . --prefix $GITHUB_WORKSPACE/proj-install

    - name: Build GDAL
      run: |
        git clone https://github.com/OSGeo/gdal.git
        cd gdal
        mkdir build-android
        cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF \
          -DOGR_BUILD_OPTIONAL_DRIVERS=OFF \
          -DPROJ_ROOT=$GITHUB_WORKSPACE/proj-install \
          -DSQLite3_INCLUDE_DIR=$GITHUB_WORKSPACE/sqlite-install/include \
          -DSQLite3_LIBRARY=$GITHUB_WORKSPACE/sqlite-install/lib/libsqlite3.a
        cmake --build .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gdal-android
        path: gdal/build-android/gdal.so