name: Build GDAL for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # or 'temurin', 'zulu', etc.
        java-package: jdk
        architecture: x64

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Add other dependencies specific to your project

    - name: Clone repository
      run: |
        git clone https://github.com/tmizu23/pdfium_build_gdal_3_8.git
        cd pdfium_build_gdal_3_8
        ls -la  # Lists all files to verify contents
        
     - name: Set up depot_tools
      run: |
        echo "${{ github.workspace }}/pdfium_build_gdal_3_8/depot_tools" >> $GITHUB_PATH

    - name: Set file permissions and run script
      run: |
        cd pdfium_build_gdal_3_8  # Make sure this is the correct path
        pwd
        chmod +x build_linux.sh
        ./build_linux.sh


    - name: Build GDAL
      run: |
        ./build_externallib_android.sh
        ./build_android.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gdal-android
        path: path/to/your/output/files
