name: GDAL Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e

    - name: Install Build Dependencies
      run: |
        sudo apt-get install -y ninja-build

    - name: Build GDAL
      run: |
        git clone https://github.com/OSGeo/gdal.git
        cd gdal
        ls -la
        ./configure --host=aarch64-linux-android --with-proj=/usr/local --with-sqlite3=/usr/local --without-libtool
        make -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gdal-android
        path: gdal/swig/java/gdal.jar